[package]
name = "kobzar"
version = "0.1.0"
edition = "2024"
authors = ["Maxym Naumchyk <max.naumch@gmail.com>"]

[dependencies]
tokio = { version = "1.45", features = ["full"] }
smallvec = { version = "1.15", features = ["union"] }
tracing = { version = "0.1", features = ["log"] }
compact_str = "0.9"
thiserror = "2.0"
marble = "16.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
ahash = "0.8"
hashbrown = "0.15"
dotenv = "0.15"
num_cpus = "1.17"
log = "0.4"
fern = { version = "0.7", features = ["colored"] }
libloading = "0.8"
